# Используем официальный образ PostgreSQL
FROM postgres:latest

# Задаем порт PostgreSQL (по умолчанию 5432)
ENV POSTGRES_PORT 5432  # Устанавливаем порт 5432

# Создаем базу данных, пользователя и устанавливаем пароль
ENV POSTGRES_DB mydatabase
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword